name: led-clock-frontend

services:
  frontend:
    image: ghcr.io/atanasovski-xyz/led-clock-frontend:latest
    hostname: led-frontend
    container_name: led-frontend
    ports:
      - "3003:3000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ledfrontend.rule=Host(`draw.atanasovski.xyz`)"
      - "traefik.http.services.ledfrontend.loadbalancer.server.port=3000"
      - "traefik.http.services.ledfrontend.loadbalancer.server.scheme=http"
      - "traefik.http.routers.ledfrontend.entryPoints=https"
    environment:
      - LED_SERVER_URL=https://led.atanasovski.xyz
