name: Deploy Frontend to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: choice
        required: true
        options:
          - "everest"
          - "aurora"
          - "tower"
        default: "everest"
      version:
        description: "Version to deploy"
        required: true
        default: "latest"
        type: string

env:
  STACK_NAME: "led-frontend"

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Connect to Tailscale network
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # Setup docker remote context
      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@v2
        with:
          ssh-host: ${{ secrets.EVEREST_HOST }}
          ssh-username: ${{ secrets.EVEREST_USERNAME }}
          ssh-private-key: ${{ secrets.EVEREST_SSH_KEY }}
          context-use: true

      # Deploy / Remove the Driver and Server services
      - name: Deploy / Remove the Driver and Server services
        run: |
          echo "Deploying version ${{ inputs.version }} to ${{ inputs.environment }} environment"

          if [ "${{ inputs.delete }}" = true ]; then
            docker compose -f .github/deploy/docker-compose.${{ inputs.environment }}.yml down
          else
            docker compose -f .github/deploy/docker-compose.${{ inputs.environment }}.yml pull
            docker compose -f .github/deploy/docker-compose.${{ inputs.environment }}.yml up -d --remove-orphans --build
          fi
